### ISSUE TITLE
Work to be done

### ISSUE THREAD

**Issue by AugustT** [BiologicalRecordsCentre/NBN4R#1]
@fozy81 Can you spend 10 minutes creating a series of tasks/issues that need to be done to improve the package/make it CRAN worthy. Create each one as a new issue if you can and try to be as specific as possible as what needs to be done. The more you create the better, lots of little issues tend to be better than 2 or 3 massive jobs! This way we can capture what is in your head and if neither of us get back to this for 3 months we will have a good starting point. It will also be a useful to show to any would be funders/contributors.

**Comment by fozy81** [comment]
Thanks, I'll take a look in the next few days and add issues :-)

**Comment by fozy81** [comment]
Finally got around to adding the issues :smile: and so our first issue is now closed... :+1:  I'm sure there's more to do but that's roughly what's in my head.
